version: '3.8'
env_file:
  - .env.dev

services:
  mongoDb:
    image: mongo:latest
    container_name: mongoDb
    volumes:
      - ./mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

  redis:
    image: redis:7.2-alpine
    container_name: redis
    volumes:
      - ./redis_data:/data
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "${REDIS_PASSWORD}"]
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    restart: unless-stopped

  emailServer:
    build:
      context: ./emailServer
      dockerfile: Dockerfile
    environment:
      - MY_EMAIL=${MY_EMAIL}
      - MY_PASSWORD=${MY_PASSWORD}
      - QUEUE_HOST=redis
      - QUEUE_PORT=6379
      - QUEUE_USER=default
      - QUEUE_PASSWORD=${QUEUE_PASSWORD}
    depends_on:
      - redis