CREATE TABLE IF NOT EXISTS accounts(
    id VARCHAR(27) PRIMARY KEY,
    UserID VARCHAR(24) NOT NULL,
    Namespace VARCHAR(50) NOT NULL,
    Name VARCHAR(100) NOT NULL,
    DockerImage VARCHAR(200) NOT NULL,
    CPU VARCHAR(20) NOT NULL,
    Memory VARCHAR(20) NOT NULL,
    Replicas INT NOT NULL,
    Port INT NOT NULL,
    Environments JSONB NOT NULL,
    CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);