apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scs-cloud-pvc
  namespace: scs-cloud
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce