// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: devService.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DevService_GetAvailableImages_FullMethodName = "/pb.DevService/GetAvailableImages"
	DevService_GetDevServices_FullMethodName     = "/pb.DevService/GetDevServices"
	DevService_GetDevService_FullMethodName      = "/pb.DevService/GetDevService"
	DevService_CreateDevService_FullMethodName   = "/pb.DevService/CreateDevService"
	DevService_DeleteDevService_FullMethodName   = "/pb.DevService/DeleteDevService"
	DevService_StopDevService_FullMethodName     = "/pb.DevService/StopDevService"
	DevService_StartDevService_FullMethodName    = "/pb.DevService/StartDevService"
)

// DevServiceClient is the client API for DevService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// functionality to be added later
type DevServiceClient interface {
	GetAvailableImages(ctx context.Context, in *GetAvailableImagesRequest, opts ...grpc.CallOption) (*GetAvailableImagesResponse, error)
	GetDevServices(ctx context.Context, in *GetDevServicesRequest, opts ...grpc.CallOption) (*GetDevServicesResponse, error)
	GetDevService(ctx context.Context, in *GetDevServiceRequest, opts ...grpc.CallOption) (*GetDevServiceResponse, error)
	CreateDevService(ctx context.Context, in *CreateDevServiceRequest, opts ...grpc.CallOption) (*CreateDevServiceResponse, error)
	DeleteDevService(ctx context.Context, in *DeleteDevServiceRequest, opts ...grpc.CallOption) (*DeleteDevServiceResponse, error)
	StopDevService(ctx context.Context, in *StopDevServiceRequest, opts ...grpc.CallOption) (*StopDevServiceResponse, error)
	StartDevService(ctx context.Context, in *StartDevServiceRequest, opts ...grpc.CallOption) (*StartDevServiceResponse, error)
}

type devServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDevServiceClient(cc grpc.ClientConnInterface) DevServiceClient {
	return &devServiceClient{cc}
}

func (c *devServiceClient) GetAvailableImages(ctx context.Context, in *GetAvailableImagesRequest, opts ...grpc.CallOption) (*GetAvailableImagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAvailableImagesResponse)
	err := c.cc.Invoke(ctx, DevService_GetAvailableImages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devServiceClient) GetDevServices(ctx context.Context, in *GetDevServicesRequest, opts ...grpc.CallOption) (*GetDevServicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDevServicesResponse)
	err := c.cc.Invoke(ctx, DevService_GetDevServices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devServiceClient) GetDevService(ctx context.Context, in *GetDevServiceRequest, opts ...grpc.CallOption) (*GetDevServiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDevServiceResponse)
	err := c.cc.Invoke(ctx, DevService_GetDevService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devServiceClient) CreateDevService(ctx context.Context, in *CreateDevServiceRequest, opts ...grpc.CallOption) (*CreateDevServiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateDevServiceResponse)
	err := c.cc.Invoke(ctx, DevService_CreateDevService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devServiceClient) DeleteDevService(ctx context.Context, in *DeleteDevServiceRequest, opts ...grpc.CallOption) (*DeleteDevServiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteDevServiceResponse)
	err := c.cc.Invoke(ctx, DevService_DeleteDevService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devServiceClient) StopDevService(ctx context.Context, in *StopDevServiceRequest, opts ...grpc.CallOption) (*StopDevServiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopDevServiceResponse)
	err := c.cc.Invoke(ctx, DevService_StopDevService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devServiceClient) StartDevService(ctx context.Context, in *StartDevServiceRequest, opts ...grpc.CallOption) (*StartDevServiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartDevServiceResponse)
	err := c.cc.Invoke(ctx, DevService_StartDevService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DevServiceServer is the server API for DevService service.
// All implementations must embed UnimplementedDevServiceServer
// for forward compatibility.
//
// functionality to be added later
type DevServiceServer interface {
	GetAvailableImages(context.Context, *GetAvailableImagesRequest) (*GetAvailableImagesResponse, error)
	GetDevServices(context.Context, *GetDevServicesRequest) (*GetDevServicesResponse, error)
	GetDevService(context.Context, *GetDevServiceRequest) (*GetDevServiceResponse, error)
	CreateDevService(context.Context, *CreateDevServiceRequest) (*CreateDevServiceResponse, error)
	DeleteDevService(context.Context, *DeleteDevServiceRequest) (*DeleteDevServiceResponse, error)
	StopDevService(context.Context, *StopDevServiceRequest) (*StopDevServiceResponse, error)
	StartDevService(context.Context, *StartDevServiceRequest) (*StartDevServiceResponse, error)
	mustEmbedUnimplementedDevServiceServer()
}

// UnimplementedDevServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDevServiceServer struct{}

func (UnimplementedDevServiceServer) GetAvailableImages(context.Context, *GetAvailableImagesRequest) (*GetAvailableImagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAvailableImages not implemented")
}
func (UnimplementedDevServiceServer) GetDevServices(context.Context, *GetDevServicesRequest) (*GetDevServicesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDevServices not implemented")
}
func (UnimplementedDevServiceServer) GetDevService(context.Context, *GetDevServiceRequest) (*GetDevServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDevService not implemented")
}
func (UnimplementedDevServiceServer) CreateDevService(context.Context, *CreateDevServiceRequest) (*CreateDevServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDevService not implemented")
}
func (UnimplementedDevServiceServer) DeleteDevService(context.Context, *DeleteDevServiceRequest) (*DeleteDevServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDevService not implemented")
}
func (UnimplementedDevServiceServer) StopDevService(context.Context, *StopDevServiceRequest) (*StopDevServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopDevService not implemented")
}
func (UnimplementedDevServiceServer) StartDevService(context.Context, *StartDevServiceRequest) (*StartDevServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartDevService not implemented")
}
func (UnimplementedDevServiceServer) mustEmbedUnimplementedDevServiceServer() {}
func (UnimplementedDevServiceServer) testEmbeddedByValue()                    {}

// UnsafeDevServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DevServiceServer will
// result in compilation errors.
type UnsafeDevServiceServer interface {
	mustEmbedUnimplementedDevServiceServer()
}

func RegisterDevServiceServer(s grpc.ServiceRegistrar, srv DevServiceServer) {
	// If the following call pancis, it indicates UnimplementedDevServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DevService_ServiceDesc, srv)
}

func _DevService_GetAvailableImages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAvailableImagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevServiceServer).GetAvailableImages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DevService_GetAvailableImages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevServiceServer).GetAvailableImages(ctx, req.(*GetAvailableImagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DevService_GetDevServices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDevServicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevServiceServer).GetDevServices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DevService_GetDevServices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevServiceServer).GetDevServices(ctx, req.(*GetDevServicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DevService_GetDevService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDevServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevServiceServer).GetDevService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DevService_GetDevService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevServiceServer).GetDevService(ctx, req.(*GetDevServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DevService_CreateDevService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDevServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevServiceServer).CreateDevService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DevService_CreateDevService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevServiceServer).CreateDevService(ctx, req.(*CreateDevServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DevService_DeleteDevService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDevServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevServiceServer).DeleteDevService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DevService_DeleteDevService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevServiceServer).DeleteDevService(ctx, req.(*DeleteDevServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DevService_StopDevService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopDevServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevServiceServer).StopDevService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DevService_StopDevService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevServiceServer).StopDevService(ctx, req.(*StopDevServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DevService_StartDevService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartDevServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevServiceServer).StartDevService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DevService_StartDevService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevServiceServer).StartDevService(ctx, req.(*StartDevServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DevService_ServiceDesc is the grpc.ServiceDesc for DevService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DevService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.DevService",
	HandlerType: (*DevServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAvailableImages",
			Handler:    _DevService_GetAvailableImages_Handler,
		},
		{
			MethodName: "GetDevServices",
			Handler:    _DevService_GetDevServices_Handler,
		},
		{
			MethodName: "GetDevService",
			Handler:    _DevService_GetDevService_Handler,
		},
		{
			MethodName: "CreateDevService",
			Handler:    _DevService_CreateDevService_Handler,
		},
		{
			MethodName: "DeleteDevService",
			Handler:    _DevService_DeleteDevService_Handler,
		},
		{
			MethodName: "StopDevService",
			Handler:    _DevService_StopDevService_Handler,
		},
		{
			MethodName: "StartDevService",
			Handler:    _DevService_StartDevService_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "devService.proto",
}
