// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: devService.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Deployment struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               *string                `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	UserId           string                 `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Namespace        string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name             string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	DevServiceName   string                 `protobuf:"bytes,5,opt,name=devServiceName,proto3" json:"devServiceName,omitempty"`
	Cpu              string                 `protobuf:"bytes,6,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Memory           string                 `protobuf:"bytes,7,opt,name=memory,proto3" json:"memory,omitempty"`
	Port             int32                  `protobuf:"varint,8,opt,name=port,proto3" json:"port,omitempty"`
	UnlockPass       string                 `protobuf:"bytes,9,opt,name=unlockPass,proto3" json:"unlockPass,omitempty"`
	CreatedAt        string                 `protobuf:"bytes,10,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	ServiceSubdomain string                 `protobuf:"bytes,12,opt,name=serviceSubdomain,proto3" json:"serviceSubdomain,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Deployment) Reset() {
	*x = Deployment{}
	mi := &file_devService_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Deployment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Deployment) ProtoMessage() {}

func (x *Deployment) ProtoReflect() protoreflect.Message {
	mi := &file_devService_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Deployment.ProtoReflect.Descriptor instead.
func (*Deployment) Descriptor() ([]byte, []int) {
	return file_devService_proto_rawDescGZIP(), []int{0}
}

func (x *Deployment) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *Deployment) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Deployment) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Deployment) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Deployment) GetDevServiceName() string {
	if x != nil {
		return x.DevServiceName
	}
	return ""
}

func (x *Deployment) GetCpu() string {
	if x != nil {
		return x.Cpu
	}
	return ""
}

func (x *Deployment) GetMemory() string {
	if x != nil {
		return x.Memory
	}
	return ""
}

func (x *Deployment) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Deployment) GetUnlockPass() string {
	if x != nil {
		return x.UnlockPass
	}
	return ""
}

func (x *Deployment) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Deployment) GetServiceSubdomain() string {
	if x != nil {
		return x.ServiceSubdomain
	}
	return ""
}

// Requests
type GetAvailableImagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAvailableImagesRequest) Reset() {
	*x = GetAvailableImagesRequest{}
	mi := &file_devService_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAvailableImagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvailableImagesRequest) ProtoMessage() {}

func (x *GetAvailableImagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_devService_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvailableImagesRequest.ProtoReflect.Descriptor instead.
func (*GetAvailableImagesRequest) Descriptor() ([]byte, []int) {
	return file_devService_proto_rawDescGZIP(), []int{1}
}

type GetDevServicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDevServicesRequest) Reset() {
	*x = GetDevServicesRequest{}
	mi := &file_devService_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDevServicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDevServicesRequest) ProtoMessage() {}

func (x *GetDevServicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_devService_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDevServicesRequest.ProtoReflect.Descriptor instead.
func (*GetDevServicesRequest) Descriptor() ([]byte, []int) {
	return file_devService_proto_rawDescGZIP(), []int{2}
}

func (x *GetDevServicesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetDevServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeploymentId  string                 `protobuf:"bytes,1,opt,name=deploymentId,proto3" json:"deploymentId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDevServiceRequest) Reset() {
	*x = GetDevServiceRequest{}
	mi := &file_devService_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDevServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDevServiceRequest) ProtoMessage() {}

func (x *GetDevServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_devService_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDevServiceRequest.ProtoReflect.Descriptor instead.
func (*GetDevServiceRequest) Descriptor() ([]byte, []int) {
	return file_devService_proto_rawDescGZIP(), []int{3}
}

func (x *GetDevServiceRequest) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

type CreateDevServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deployment    *Deployment            `protobuf:"bytes,1,opt,name=deployment,proto3" json:"deployment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDevServiceRequest) Reset() {
	*x = CreateDevServiceRequest{}
	mi := &file_devService_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDevServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDevServiceRequest) ProtoMessage() {}

func (x *CreateDevServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_devService_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDevServiceRequest.ProtoReflect.Descriptor instead.
func (*CreateDevServiceRequest) Descriptor() ([]byte, []int) {
	return file_devService_proto_rawDescGZIP(), []int{4}
}

func (x *CreateDevServiceRequest) GetDeployment() *Deployment {
	if x != nil {
		return x.Deployment
	}
	return nil
}

type DeleteDevServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeploymentId  string                 `protobuf:"bytes,1,opt,name=deploymentId,proto3" json:"deploymentId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDevServiceRequest) Reset() {
	*x = DeleteDevServiceRequest{}
	mi := &file_devService_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDevServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDevServiceRequest) ProtoMessage() {}

func (x *DeleteDevServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_devService_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDevServiceRequest.ProtoReflect.Descriptor instead.
func (*DeleteDevServiceRequest) Descriptor() ([]byte, []int) {
	return file_devService_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteDevServiceRequest) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

type StopDevServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeploymentId  string                 `protobuf:"bytes,1,opt,name=deploymentId,proto3" json:"deploymentId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopDevServiceRequest) Reset() {
	*x = StopDevServiceRequest{}
	mi := &file_devService_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopDevServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopDevServiceRequest) ProtoMessage() {}

func (x *StopDevServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_devService_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopDevServiceRequest.ProtoReflect.Descriptor instead.
func (*StopDevServiceRequest) Descriptor() ([]byte, []int) {
	return file_devService_proto_rawDescGZIP(), []int{6}
}

func (x *StopDevServiceRequest) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

type StartDevServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeploymentId  string                 `protobuf:"bytes,1,opt,name=deploymentId,proto3" json:"deploymentId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartDevServiceRequest) Reset() {
	*x = StartDevServiceRequest{}
	mi := &file_devService_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartDevServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartDevServiceRequest) ProtoMessage() {}

func (x *StartDevServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_devService_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartDevServiceRequest.ProtoReflect.Descriptor instead.
func (*StartDevServiceRequest) Descriptor() ([]byte, []int) {
	return file_devService_proto_rawDescGZIP(), []int{7}
}

func (x *StartDevServiceRequest) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

// Responses
type GetAvailableImagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Images        []string               `protobuf:"bytes,1,rep,name=images,proto3" json:"images,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAvailableImagesResponse) Reset() {
	*x = GetAvailableImagesResponse{}
	mi := &file_devService_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAvailableImagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvailableImagesResponse) ProtoMessage() {}

func (x *GetAvailableImagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_devService_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvailableImagesResponse.ProtoReflect.Descriptor instead.
func (*GetAvailableImagesResponse) Descriptor() ([]byte, []int) {
	return file_devService_proto_rawDescGZIP(), []int{8}
}

func (x *GetAvailableImagesResponse) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

type GetDevServicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deployments   []*Deployment          `protobuf:"bytes,1,rep,name=deployments,proto3" json:"deployments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDevServicesResponse) Reset() {
	*x = GetDevServicesResponse{}
	mi := &file_devService_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDevServicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDevServicesResponse) ProtoMessage() {}

func (x *GetDevServicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_devService_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDevServicesResponse.ProtoReflect.Descriptor instead.
func (*GetDevServicesResponse) Descriptor() ([]byte, []int) {
	return file_devService_proto_rawDescGZIP(), []int{9}
}

func (x *GetDevServicesResponse) GetDeployments() []*Deployment {
	if x != nil {
		return x.Deployments
	}
	return nil
}

type GetDevServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deployment    *Deployment            `protobuf:"bytes,1,opt,name=deployment,proto3" json:"deployment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDevServiceResponse) Reset() {
	*x = GetDevServiceResponse{}
	mi := &file_devService_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDevServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDevServiceResponse) ProtoMessage() {}

func (x *GetDevServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_devService_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDevServiceResponse.ProtoReflect.Descriptor instead.
func (*GetDevServiceResponse) Descriptor() ([]byte, []int) {
	return file_devService_proto_rawDescGZIP(), []int{10}
}

func (x *GetDevServiceResponse) GetDeployment() *Deployment {
	if x != nil {
		return x.Deployment
	}
	return nil
}

type CreateDevServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deployment    *Deployment            `protobuf:"bytes,1,opt,name=deployment,proto3" json:"deployment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDevServiceResponse) Reset() {
	*x = CreateDevServiceResponse{}
	mi := &file_devService_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDevServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDevServiceResponse) ProtoMessage() {}

func (x *CreateDevServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_devService_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDevServiceResponse.ProtoReflect.Descriptor instead.
func (*CreateDevServiceResponse) Descriptor() ([]byte, []int) {
	return file_devService_proto_rawDescGZIP(), []int{11}
}

func (x *CreateDevServiceResponse) GetDeployment() *Deployment {
	if x != nil {
		return x.Deployment
	}
	return nil
}

type DeleteDevServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDevServiceResponse) Reset() {
	*x = DeleteDevServiceResponse{}
	mi := &file_devService_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDevServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDevServiceResponse) ProtoMessage() {}

func (x *DeleteDevServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_devService_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDevServiceResponse.ProtoReflect.Descriptor instead.
func (*DeleteDevServiceResponse) Descriptor() ([]byte, []int) {
	return file_devService_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteDevServiceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StartDevServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartDevServiceResponse) Reset() {
	*x = StartDevServiceResponse{}
	mi := &file_devService_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartDevServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartDevServiceResponse) ProtoMessage() {}

func (x *StartDevServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_devService_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartDevServiceResponse.ProtoReflect.Descriptor instead.
func (*StartDevServiceResponse) Descriptor() ([]byte, []int) {
	return file_devService_proto_rawDescGZIP(), []int{13}
}

func (x *StartDevServiceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StopDevServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopDevServiceResponse) Reset() {
	*x = StopDevServiceResponse{}
	mi := &file_devService_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopDevServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopDevServiceResponse) ProtoMessage() {}

func (x *StopDevServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_devService_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopDevServiceResponse.ProtoReflect.Descriptor instead.
func (*StopDevServiceResponse) Descriptor() ([]byte, []int) {
	return file_devService_proto_rawDescGZIP(), []int{14}
}

func (x *StopDevServiceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_devService_proto protoreflect.FileDescriptor

const file_devService_proto_rawDesc = "" +
	"\n" +
	"\x10devService.proto\x12\x02pb\"\xc2\x02\n" +
	"\n" +
	"Deployment\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x88\x01\x01\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\tR\x06userId\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12&\n" +
	"\x0edevServiceName\x18\x05 \x01(\tR\x0edevServiceName\x12\x10\n" +
	"\x03cpu\x18\x06 \x01(\tR\x03cpu\x12\x16\n" +
	"\x06memory\x18\a \x01(\tR\x06memory\x12\x12\n" +
	"\x04port\x18\b \x01(\x05R\x04port\x12\x1e\n" +
	"\n" +
	"unlockPass\x18\t \x01(\tR\n" +
	"unlockPass\x12\x1c\n" +
	"\tcreatedAt\x18\n" +
	" \x01(\tR\tcreatedAt\x12*\n" +
	"\x10serviceSubdomain\x18\f \x01(\tR\x10serviceSubdomainB\x05\n" +
	"\x03_id\"\x1b\n" +
	"\x19GetAvailableImagesRequest\"/\n" +
	"\x15GetDevServicesRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\":\n" +
	"\x14GetDevServiceRequest\x12\"\n" +
	"\fdeploymentId\x18\x01 \x01(\tR\fdeploymentId\"I\n" +
	"\x17CreateDevServiceRequest\x12.\n" +
	"\n" +
	"deployment\x18\x01 \x01(\v2\x0e.pb.DeploymentR\n" +
	"deployment\"=\n" +
	"\x17DeleteDevServiceRequest\x12\"\n" +
	"\fdeploymentId\x18\x01 \x01(\tR\fdeploymentId\";\n" +
	"\x15StopDevServiceRequest\x12\"\n" +
	"\fdeploymentId\x18\x01 \x01(\tR\fdeploymentId\"<\n" +
	"\x16StartDevServiceRequest\x12\"\n" +
	"\fdeploymentId\x18\x01 \x01(\tR\fdeploymentId\"4\n" +
	"\x1aGetAvailableImagesResponse\x12\x16\n" +
	"\x06images\x18\x01 \x03(\tR\x06images\"J\n" +
	"\x16GetDevServicesResponse\x120\n" +
	"\vdeployments\x18\x01 \x03(\v2\x0e.pb.DeploymentR\vdeployments\"G\n" +
	"\x15GetDevServiceResponse\x12.\n" +
	"\n" +
	"deployment\x18\x01 \x01(\v2\x0e.pb.DeploymentR\n" +
	"deployment\"J\n" +
	"\x18CreateDevServiceResponse\x12.\n" +
	"\n" +
	"deployment\x18\x01 \x01(\v2\x0e.pb.DeploymentR\n" +
	"deployment\"4\n" +
	"\x18DeleteDevServiceResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"3\n" +
	"\x17StartDevServiceResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"2\n" +
	"\x16StopDevServiceResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xa3\x04\n" +
	"\n" +
	"DevService\x12S\n" +
	"\x12GetAvailableImages\x12\x1d.pb.GetAvailableImagesRequest\x1a\x1e.pb.GetAvailableImagesResponse\x12G\n" +
	"\x0eGetDevServices\x12\x19.pb.GetDevServicesRequest\x1a\x1a.pb.GetDevServicesResponse\x12D\n" +
	"\rGetDevService\x12\x18.pb.GetDevServiceRequest\x1a\x19.pb.GetDevServiceResponse\x12M\n" +
	"\x10CreateDevService\x12\x1b.pb.CreateDevServiceRequest\x1a\x1c.pb.CreateDevServiceResponse\x12M\n" +
	"\x10DeleteDevService\x12\x1b.pb.DeleteDevServiceRequest\x1a\x1c.pb.DeleteDevServiceResponse\x12G\n" +
	"\x0eStopDevService\x12\x19.pb.StopDevServiceRequest\x1a\x1a.pb.StopDevServiceResponse\x12J\n" +
	"\x0fStartDevService\x12\x1a.pb.StartDevServiceRequest\x1a\x1b.pb.StartDevServiceResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_devService_proto_rawDescOnce sync.Once
	file_devService_proto_rawDescData []byte
)

func file_devService_proto_rawDescGZIP() []byte {
	file_devService_proto_rawDescOnce.Do(func() {
		file_devService_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_devService_proto_rawDesc), len(file_devService_proto_rawDesc)))
	})
	return file_devService_proto_rawDescData
}

var file_devService_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_devService_proto_goTypes = []any{
	(*Deployment)(nil),                 // 0: pb.Deployment
	(*GetAvailableImagesRequest)(nil),  // 1: pb.GetAvailableImagesRequest
	(*GetDevServicesRequest)(nil),      // 2: pb.GetDevServicesRequest
	(*GetDevServiceRequest)(nil),       // 3: pb.GetDevServiceRequest
	(*CreateDevServiceRequest)(nil),    // 4: pb.CreateDevServiceRequest
	(*DeleteDevServiceRequest)(nil),    // 5: pb.DeleteDevServiceRequest
	(*StopDevServiceRequest)(nil),      // 6: pb.StopDevServiceRequest
	(*StartDevServiceRequest)(nil),     // 7: pb.StartDevServiceRequest
	(*GetAvailableImagesResponse)(nil), // 8: pb.GetAvailableImagesResponse
	(*GetDevServicesResponse)(nil),     // 9: pb.GetDevServicesResponse
	(*GetDevServiceResponse)(nil),      // 10: pb.GetDevServiceResponse
	(*CreateDevServiceResponse)(nil),   // 11: pb.CreateDevServiceResponse
	(*DeleteDevServiceResponse)(nil),   // 12: pb.DeleteDevServiceResponse
	(*StartDevServiceResponse)(nil),    // 13: pb.StartDevServiceResponse
	(*StopDevServiceResponse)(nil),     // 14: pb.StopDevServiceResponse
}
var file_devService_proto_depIdxs = []int32{
	0,  // 0: pb.CreateDevServiceRequest.deployment:type_name -> pb.Deployment
	0,  // 1: pb.GetDevServicesResponse.deployments:type_name -> pb.Deployment
	0,  // 2: pb.GetDevServiceResponse.deployment:type_name -> pb.Deployment
	0,  // 3: pb.CreateDevServiceResponse.deployment:type_name -> pb.Deployment
	1,  // 4: pb.DevService.GetAvailableImages:input_type -> pb.GetAvailableImagesRequest
	2,  // 5: pb.DevService.GetDevServices:input_type -> pb.GetDevServicesRequest
	3,  // 6: pb.DevService.GetDevService:input_type -> pb.GetDevServiceRequest
	4,  // 7: pb.DevService.CreateDevService:input_type -> pb.CreateDevServiceRequest
	5,  // 8: pb.DevService.DeleteDevService:input_type -> pb.DeleteDevServiceRequest
	6,  // 9: pb.DevService.StopDevService:input_type -> pb.StopDevServiceRequest
	7,  // 10: pb.DevService.StartDevService:input_type -> pb.StartDevServiceRequest
	8,  // 11: pb.DevService.GetAvailableImages:output_type -> pb.GetAvailableImagesResponse
	9,  // 12: pb.DevService.GetDevServices:output_type -> pb.GetDevServicesResponse
	10, // 13: pb.DevService.GetDevService:output_type -> pb.GetDevServiceResponse
	11, // 14: pb.DevService.CreateDevService:output_type -> pb.CreateDevServiceResponse
	12, // 15: pb.DevService.DeleteDevService:output_type -> pb.DeleteDevServiceResponse
	14, // 16: pb.DevService.StopDevService:output_type -> pb.StopDevServiceResponse
	13, // 17: pb.DevService.StartDevService:output_type -> pb.StartDevServiceResponse
	11, // [11:18] is the sub-list for method output_type
	4,  // [4:11] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_devService_proto_init() }
func file_devService_proto_init() {
	if File_devService_proto != nil {
		return
	}
	file_devService_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_devService_proto_rawDesc), len(file_devService_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_devService_proto_goTypes,
		DependencyIndexes: file_devService_proto_depIdxs,
		MessageInfos:      file_devService_proto_msgTypes,
	}.Build()
	File_devService_proto = out.File
	file_devService_proto_goTypes = nil
	file_devService_proto_depIdxs = nil
}
