version: '3.8'

services:
  s3:
    image: minio/minio
    container_name: minio
    environment:
      - MINIO_ROOT_USER=l3snnzxhs3
      - MINIO_ROOT_PASSWORD=gmtgl9dlt1e
    ports:
      # Map the API port (for S3 clients)
      - "9000:9000"
    volumes:
      - ./minio_data:/data
    # The command to start the MinIO server and enable the console
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 30s
      timeout: 20s
      retries: 3


