// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: containerService.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetDeploymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeploymentRequest) Reset() {
	*x = GetDeploymentRequest{}
	mi := &file_containerService_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeploymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeploymentRequest) ProtoMessage() {}

func (x *GetDeploymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_containerService_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeploymentRequest.ProtoReflect.Descriptor instead.
func (*GetDeploymentRequest) Descriptor() ([]byte, []int) {
	return file_containerService_proto_rawDescGZIP(), []int{0}
}

func (x *GetDeploymentRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetDeploymentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deployments   []*Deployment          `protobuf:"bytes,1,rep,name=deployments,proto3" json:"deployments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeploymentsResponse) Reset() {
	*x = GetDeploymentsResponse{}
	mi := &file_containerService_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeploymentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeploymentsResponse) ProtoMessage() {}

func (x *GetDeploymentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_containerService_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeploymentsResponse.ProtoReflect.Descriptor instead.
func (*GetDeploymentsResponse) Descriptor() ([]byte, []int) {
	return file_containerService_proto_rawDescGZIP(), []int{1}
}

func (x *GetDeploymentsResponse) GetDeployments() []*Deployment {
	if x != nil {
		return x.Deployments
	}
	return nil
}

type Deployment struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               *string                `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	Namespace        string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name             string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	DockerImage      string                 `protobuf:"bytes,4,opt,name=docker_image,json=dockerImage,proto3" json:"docker_image,omitempty"`
	Cpu              string                 `protobuf:"bytes,5,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Memory           string                 `protobuf:"bytes,6,opt,name=memory,proto3" json:"memory,omitempty"`
	Replicas         int32                  `protobuf:"varint,7,opt,name=replicas,proto3" json:"replicas,omitempty"`
	Port             int32                  `protobuf:"varint,8,opt,name=port,proto3" json:"port,omitempty"`
	Environments     map[string]string      `protobuf:"bytes,9,rep,name=environments,proto3" json:"environments,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreatedAt        string                 `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ServiceSubdomain *string                `protobuf:"bytes,11,opt,name=serviceSubdomain,proto3,oneof" json:"serviceSubdomain,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Deployment) Reset() {
	*x = Deployment{}
	mi := &file_containerService_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Deployment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Deployment) ProtoMessage() {}

func (x *Deployment) ProtoReflect() protoreflect.Message {
	mi := &file_containerService_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Deployment.ProtoReflect.Descriptor instead.
func (*Deployment) Descriptor() ([]byte, []int) {
	return file_containerService_proto_rawDescGZIP(), []int{2}
}

func (x *Deployment) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *Deployment) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Deployment) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Deployment) GetDockerImage() string {
	if x != nil {
		return x.DockerImage
	}
	return ""
}

func (x *Deployment) GetCpu() string {
	if x != nil {
		return x.Cpu
	}
	return ""
}

func (x *Deployment) GetMemory() string {
	if x != nil {
		return x.Memory
	}
	return ""
}

func (x *Deployment) GetReplicas() int32 {
	if x != nil {
		return x.Replicas
	}
	return 0
}

func (x *Deployment) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Deployment) GetEnvironments() map[string]string {
	if x != nil {
		return x.Environments
	}
	return nil
}

func (x *Deployment) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Deployment) GetServiceSubdomain() string {
	if x != nil && x.ServiceSubdomain != nil {
		return *x.ServiceSubdomain
	}
	return ""
}

type PostDeploymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Deployment    *Deployment            `protobuf:"bytes,2,opt,name=deployment,proto3" json:"deployment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostDeploymentRequest) Reset() {
	*x = PostDeploymentRequest{}
	mi := &file_containerService_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostDeploymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostDeploymentRequest) ProtoMessage() {}

func (x *PostDeploymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_containerService_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostDeploymentRequest.ProtoReflect.Descriptor instead.
func (*PostDeploymentRequest) Descriptor() ([]byte, []int) {
	return file_containerService_proto_rawDescGZIP(), []int{3}
}

func (x *PostDeploymentRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PostDeploymentRequest) GetDeployment() *Deployment {
	if x != nil {
		return x.Deployment
	}
	return nil
}

type PostDeploymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Deployment    *Deployment            `protobuf:"bytes,2,opt,name=deployment,proto3" json:"deployment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostDeploymentResponse) Reset() {
	*x = PostDeploymentResponse{}
	mi := &file_containerService_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostDeploymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostDeploymentResponse) ProtoMessage() {}

func (x *PostDeploymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_containerService_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostDeploymentResponse.ProtoReflect.Descriptor instead.
func (*PostDeploymentResponse) Descriptor() ([]byte, []int) {
	return file_containerService_proto_rawDescGZIP(), []int{4}
}

func (x *PostDeploymentResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PostDeploymentResponse) GetDeployment() *Deployment {
	if x != nil {
		return x.Deployment
	}
	return nil
}

type DeleteDeploymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDeploymentRequest) Reset() {
	*x = DeleteDeploymentRequest{}
	mi := &file_containerService_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDeploymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDeploymentRequest) ProtoMessage() {}

func (x *DeleteDeploymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_containerService_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDeploymentRequest.ProtoReflect.Descriptor instead.
func (*DeleteDeploymentRequest) Descriptor() ([]byte, []int) {
	return file_containerService_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteDeploymentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteDeploymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDeploymentResponse) Reset() {
	*x = DeleteDeploymentResponse{}
	mi := &file_containerService_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDeploymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDeploymentResponse) ProtoMessage() {}

func (x *DeleteDeploymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_containerService_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDeploymentResponse.ProtoReflect.Descriptor instead.
func (*DeleteDeploymentResponse) Descriptor() ([]byte, []int) {
	return file_containerService_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteDeploymentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_containerService_proto protoreflect.FileDescriptor

const file_containerService_proto_rawDesc = "" +
	"\n" +
	"\x16containerService.proto\x12\x02pb\"/\n" +
	"\x14GetDeploymentRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"J\n" +
	"\x16GetDeploymentsResponse\x120\n" +
	"\vdeployments\x18\x01 \x03(\v2\x0e.pb.DeploymentR\vdeployments\"\xc3\x03\n" +
	"\n" +
	"Deployment\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x88\x01\x01\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12!\n" +
	"\fdocker_image\x18\x04 \x01(\tR\vdockerImage\x12\x10\n" +
	"\x03cpu\x18\x05 \x01(\tR\x03cpu\x12\x16\n" +
	"\x06memory\x18\x06 \x01(\tR\x06memory\x12\x1a\n" +
	"\breplicas\x18\a \x01(\x05R\breplicas\x12\x12\n" +
	"\x04port\x18\b \x01(\x05R\x04port\x12D\n" +
	"\fenvironments\x18\t \x03(\v2 .pb.Deployment.EnvironmentsEntryR\fenvironments\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\tR\tcreatedAt\x12/\n" +
	"\x10serviceSubdomain\x18\v \x01(\tH\x01R\x10serviceSubdomain\x88\x01\x01\x1a?\n" +
	"\x11EnvironmentsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x05\n" +
	"\x03_idB\x13\n" +
	"\x11_serviceSubdomain\"`\n" +
	"\x15PostDeploymentRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12.\n" +
	"\n" +
	"deployment\x18\x02 \x01(\v2\x0e.pb.DeploymentR\n" +
	"deployment\"X\n" +
	"\x16PostDeploymentResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12.\n" +
	"\n" +
	"deployment\x18\x02 \x01(\v2\x0e.pb.DeploymentR\n" +
	"deployment\")\n" +
	"\x17DeleteDeploymentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"4\n" +
	"\x18DeleteDeploymentResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xf4\x01\n" +
	"\x10ContainerService\x12F\n" +
	"\x0eGetDeployments\x12\x18.pb.GetDeploymentRequest\x1a\x1a.pb.GetDeploymentsResponse\x12I\n" +
	"\x10CreateDeployment\x12\x19.pb.PostDeploymentRequest\x1a\x1a.pb.PostDeploymentResponse\x12M\n" +
	"\x10DeleteDeployment\x12\x1b.pb.DeleteDeploymentRequest\x1a\x1c.pb.DeleteDeploymentResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_containerService_proto_rawDescOnce sync.Once
	file_containerService_proto_rawDescData []byte
)

func file_containerService_proto_rawDescGZIP() []byte {
	file_containerService_proto_rawDescOnce.Do(func() {
		file_containerService_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_containerService_proto_rawDesc), len(file_containerService_proto_rawDesc)))
	})
	return file_containerService_proto_rawDescData
}

var file_containerService_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_containerService_proto_goTypes = []any{
	(*GetDeploymentRequest)(nil),     // 0: pb.GetDeploymentRequest
	(*GetDeploymentsResponse)(nil),   // 1: pb.GetDeploymentsResponse
	(*Deployment)(nil),               // 2: pb.Deployment
	(*PostDeploymentRequest)(nil),    // 3: pb.PostDeploymentRequest
	(*PostDeploymentResponse)(nil),   // 4: pb.PostDeploymentResponse
	(*DeleteDeploymentRequest)(nil),  // 5: pb.DeleteDeploymentRequest
	(*DeleteDeploymentResponse)(nil), // 6: pb.DeleteDeploymentResponse
	nil,                              // 7: pb.Deployment.EnvironmentsEntry
}
var file_containerService_proto_depIdxs = []int32{
	2, // 0: pb.GetDeploymentsResponse.deployments:type_name -> pb.Deployment
	7, // 1: pb.Deployment.environments:type_name -> pb.Deployment.EnvironmentsEntry
	2, // 2: pb.PostDeploymentRequest.deployment:type_name -> pb.Deployment
	2, // 3: pb.PostDeploymentResponse.deployment:type_name -> pb.Deployment
	0, // 4: pb.ContainerService.GetDeployments:input_type -> pb.GetDeploymentRequest
	3, // 5: pb.ContainerService.CreateDeployment:input_type -> pb.PostDeploymentRequest
	5, // 6: pb.ContainerService.DeleteDeployment:input_type -> pb.DeleteDeploymentRequest
	1, // 7: pb.ContainerService.GetDeployments:output_type -> pb.GetDeploymentsResponse
	4, // 8: pb.ContainerService.CreateDeployment:output_type -> pb.PostDeploymentResponse
	6, // 9: pb.ContainerService.DeleteDeployment:output_type -> pb.DeleteDeploymentResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_containerService_proto_init() }
func file_containerService_proto_init() {
	if File_containerService_proto != nil {
		return
	}
	file_containerService_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_containerService_proto_rawDesc), len(file_containerService_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_containerService_proto_goTypes,
		DependencyIndexes: file_containerService_proto_depIdxs,
		MessageInfos:      file_containerService_proto_msgTypes,
	}.Build()
	File_containerService_proto = out.File
	file_containerService_proto_goTypes = nil
	file_containerService_proto_depIdxs = nil
}
